version: '3'

dotenv: ['.env']

vars:
  SCHEMA_DIR: "{{.TASKFILE_DIR}}/internal/database/sql/schema"

tasks:
  db:stop:
    cmds:
      - docker compose down
    silent: true

  db:migrate:
    dir: "{{.SCHEMA_DIR}}"
    cmds:
      - cmd: goose up
        silent: true

  db:migrate:create:
    dir: "{{.SCHEMA_DIR}}"
    cmds:
      - cmd: goose create {{.CLI_ARGS}} sql
        silent: true

  db:migrate:down:
    dir: "{{.SCHEMA_DIR}}"
    cmds:
      - cmd: goose down
        silent: true

  db:start:
    cmds:
      - docker compose up -d
    silent: true
