name: Node Setup
description: Bootstraps node and pnpm, and installs dependencies

runs:
  using: 'composite'
  steps:
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get pnpm cache directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Set up pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
